name: Python Workflow2

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest
    curl
  steps: 

    -name: checkout
     uses: actions/checkout@v4

    -name: python installation
     uses: actions/setup-python@v5
      with:
        python-version : 3.13

    -name: install dependencies
     run: |
      pip install -r requirements.txt

    -name: execute python script
     run: |
       python app.py
       sleep 5 
       curl -f http://127.0.0.1:5000 || exit 1

     
    
